version: '2'
checks:
  complex-logic:
    enabled: false
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 70
    eslint:
      enabled: true
  similar-code:
    config:
      threshold: 75
  identical-code:
    config:
      threshold: 75

exclude_patterns:
  - '**/package-lock.json/'
  - '**/.env/*'
  - '**/test/*'
  - '**/tests/*'
  - '**/dist/*'
  - '**/coverage/*'
