version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/testdb
    depends_on:
      - db
    command: ["npm", "test"]
