version: "3"

services:

  database:
    image: "postgres"
    env_file: .env
    ports:
    - ${DOCKER_POSTGRES_PORT}:${POSTGRES_PORT}

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

    volumes:
      - db-data:var/lib/postgres

  app:
    image: e-commerce-bitcrafters-bn
    depends_on:
      - database

    env_file: .env

    environment:
      POSTGRES_HOST: "database"
      POSTGRES_PORT: $PORT
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

    stdin_open: true
    tty: true
    ports:
     - ${DOCKER_LOCAL_PORT}:${PORT}

    command: npm run start

    volumes:
      - ./:/usr/src/app  