version: 2
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: postgres:13
        environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5435:5432
      - image: cimg/node:18.17.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apt-get update
            apt-get install -y docker-compose
      - run:
          name: Install npm and curl
          command: |
            apt-get update
            apt-get install -y npm curl
      - run:
          name: update-npm
          command: 'npm install -g npm@latest'
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
          when: always
      - run:
          name: Run coverage
          command: npm run coverage
          when: always
      - run:
          name: Upload coverage to Coveralls
          command: npx coveralls < coverage/lcov.info
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always
      - run:
          name: Send coverage report to Code Climate
          command: ./cc-test-reporter after-build -t lcov
          when: always
      - store_artifacts:
          path: ./coverage/lcov.info
          prefix: tests
