"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.div = exports.multiply = exports.sub = exports.sum = void 0;
const sum = (a, b) => a + b;
exports.sum = sum;
const sub = (a, b) => a - b;
exports.sub = sub;
const multiply = (a, b) => a * b;
exports.multiply = multiply;
const div = (a, b) => a / b;
exports.div = div;
