name: codeClimate CI
on:
  push:
    branches:
      - develop
    tags:
      - '!*' # Do not execute on tags
    paths:
      - src/*
      - test/*
      - '*.json'
  pull_request:
    paths:
      - '!*.MD'
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node-version: [18.x]
    name: test/node ${{ matrix.node-version }}/${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm  test
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm install
    - name: Upload test report to Code Climate
      uses: atlp-rwanda/e-commerce-bitcrafters-bn@develop
      id: codeclimate
      env:
        CC_TEST_REPORTER_ID: 9d80c597677ee5de28d25a5d0c55a99e5f2aa56305ccc14745665d9121a05817
      with:
        coverageCommand: npm run test
        debug: true
    - name: Check if test report uploaded successfully
      if: steps.codeclimate.outputs.exit-code == 0
      run: echo "Test report uploaded successfully!"
