name: CI/CD

on:
  push:
    branches: ['Develop']
  pull_request:
    branches: ['Develop']

env:
  REACT_APP_SERVER_URL: http://127.0.0.1:5002

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
